### ISSUE TITLE
Emitting an event from inside a custom input

### ISSUE THREAD

**Issue by paulogr** [wearebraid/vue-formulate#102]
**Describe the bug**
I have create a custom input radio with a button that emit an event using $emit, but the event doesn't reach the outer component.

**To Reproduce**
<MyCustomComponent @myEvent="eventMethod($event)" />

eventMethod is never fired.

**Expected behavior**
When emit an event inside a custom input the event should reach the outer component.

**Screenshots**

![Screen Shot 2020-06-02 at 15 49 33](https://user-images.githubusercontent.com/30919/83559557-226c1580-a4eb-11ea-8c9e-05440b045cb4.png)

the event is fired when I click on "Cancelar agendamento"

Thanks!

**Comment by justin-schroeder** [comment]
Sweet custom fields @paulogr! They look awesome.

As for the events...sadly this is a limitation of Vue unfortunately. Unlike the DOM there is no event bubbling in Vue. There only way I'm aware of that we could address this is by adding our own emitter function in the context object. Maybe something like `context.rootEmit(event, payload)`.

That seems like it would be pretty usable right?

**Comment by paulogr** [comment]
Thank you @justin-schroeder !

I'm not sure how `context.rootEmit` should be implemented... are you thinking something like `this.$root.$emit(event, payload)` ?

**Comment by justin-schroeder** [comment]
So I just published `v2.3.4` which included the new `context.rootEmit`. Using it should be pretty easy. In your custom input component, you are passed the `context` object as a prop. That context object will have a function in it called `rootEmit`. Use that instead of `$emit` and it will trigger an event from the top level `<FormulateInput>` component.

(I closed this but feel free to comment if you need more help)

**Comment by paulogr** [comment]
Uow, that was fast!

Thank you man, just updated my project worked pretty well.

Let me know if you need any help with VueFormulate.
