### ISSUE TITLE
Not able to change the font-size and font-weight for the input-class

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#143]
input-class="ml-2 text-lg font-bold" // Ony margin-left works
help-class="ml-2 text-lg font-bold" // Everything works

**Comment by justin-schroeder** [comment]
These issues aren't related to vue formulate, just normal styling stuff. Maybe checkout the tailwind discord server? https://tailwindcss.com/community

**Comment by Rednas83** [comment]
I am not sure if this is tailwind related because the help-class is working fine. The problem is somehow related to the input-class I think.

**Comment by justin-schroeder** [comment]
I assume you're mixing tailwind with snow again? Its really not made to do that. If that's the path you want to go down i would recommend writing your own css styles instead of using tailwind, but the issue is not related to vue formulate. If you really think it is then please provide a reproduction _where you don't use the snow theme at all_ and I’ll take a look. Good luck! 👍

**Comment by Rednas83** [comment]
I managed
https://codesandbox.io/s/tailwind-vue-formulate-1-simple-8722j?file=/src/components/Demo-01.vue

Thanks for learning me the hard way. I expected the local/id based style to overrule the global snow style.

Are there plans for a default tailwind base theme just like snow? ..I was pretty happy with snow😢

**Comment by justin-schroeder** [comment]
Glad you got it working 🎉

Not sure if we’ll do default themes for tailwind, they would be pretty easy to do as a plug-in. 🤷‍♂️ maybe...

But if you like snow, use it! Tailwind is by homeland the “preferred” way to do things. I don’t even use it myself. personally I just write css. We just needed to make sure tailwind had a strong solution since it has a big user base in the Vue community
