### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by leokyohan** [wearebraid/vue-formulate#151]
Is there an option to give the date format for vue-formulate? If it is not there it would be a really good option to give it.
I was trying to give date format MM-DD-YYYY. But by default it i coming in DD-MM-YYYY format.

**Comment by justin-schroeder** [comment]
Can you give an example of the code you’re referring to? Is this about validation rules?

**Comment by justin-schroeder** [comment]
I'm going to close this request since i've gotten no feedback on it. Feel free to respond in the future

**Comment by leokyohan** [comment]
Sorry for the late response. 

I was trying to do the below code.

    <FormulateInput
  type="date"
  name="DOB"
  label="DATE OF BIRTH"
  placeholder="MM/DD/YYYY"
  help="Enter in the format MM/DD/YYYY"
  validation="required|date:MM/DD/YYYY"
/>
But the calendar input is coming as in the below image in dd/mm/yyyy format.

![image](https://user-images.githubusercontent.com/64547308/86807048-1994d380-c097-11ea-8a96-4d796ae23e34.png)

So the input itself I'm not able to give in MM/DD/YYYY format. So is there anyway to specify the format for the input calendar?

**Comment by justin-schroeder** [comment]
Ahh, gotchya. So this is a native date input, details are here:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

So what you see is based on your browser's locale.

**Comment by leokyohan** [comment]
oh okay. So basically if I have to change the input format, I'll have to change the browser local date format. Right?

**Comment by hmaesta** [comment]
> I'll have to change the browser local date format. Right?

You should let the browser decides what is best for the user – since it's the most common format for him and this can prevent mistakes (and no matter how many times you write instructions, users simply don't read).

If this format is really necessary, you should handle (and format accordingly) on your back-end. 

And if your project is focused to US [– since this is the only country that uses MM-DD-YYYY –](https://en.m.wikipedia.org/wiki/Date_format_by_country#Usage_map) for US-users will be `MM-DD-YYYY` by default. You can change your browser language/locale to see it.

Btw, I don't think you should stress about this –– and yes by the fact that Safari (desktop) doesn't have date input and [neither will have on next version.](https://caniuse.com/#feat=input-datetime)

**Comment by leokyohan** [comment]
okay..thanks for the detailed explanation and inputs. :)

**Comment by webwaldo** [comment]
Hey, having a similar issue with the date field, what is the recommendation if you want to collect a valid date in a specific format, since the native date field looks to allow non existent  dates, and also doesn't display on Safari ? 

Ideally I am after a masked input that can validate a specified date-format.

**Comment by hmaesta** [comment]
@webwaldo The short answer is: vue-formulate does not support what you need, since it's just the HTML 5 native date-picker ([documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)).

If you need something better then the native HTML 5 date-picker you should use specific components for that propose, like  [vue-flatpickr-component](https://github.com/ankurk91/vue-flatpickr-component) or [v-calendar](https://github.com/nathanreyes/v-calendar)

**Comment by webwaldo** [comment]
Kk, thanks @hmaesta  - I am looking to use the formulate schema to build out my form, so am I right in thinking I should be able to use one of those plugins to build out a custom input via https://vueformulate.com/guide/inputs/custom-inputs/ - which I can then use from the schema?

**Comment by FrittenKeeZ** [comment]
@hmaesta is it possible ti specify the date format displayed in the validation error messages, like the `after` rule?
Currently the displayed value of the date field does not always use the same format as the value itself (often ISO).
Maybe a hook to provide date format in configuration would be nice? Or a way to take in the native value and format solely for errors.

**Comment by hmaesta** [comment]
@FrittenKeeZ Sorry, but I honestly don't know. I am currently using [vue-flatpickr-component](https://github.com/ankurk91/vue-flatpickr-component) because I need date-range, something that the native HTML5 input does not offer.

ping @justin-schroeder

**Comment by justin-schroeder** [comment]
@FrittenKeeZ yep, pretty easy to customize the messages. Read this section of the docs:

https://vueformulate.com/guide/validation/#customize-validation-messages

Vue Formulate does not include a date format library like dayjs (for obvious weight reasons) so string-interpreted date formatting for validation messages is not on the table for the default error messages, but it would be pretty easy to do by with a per-input or global override.
