### ISSUE TITLE
Should `@validation` fire on-load, or before `blur` event is fired?

### ISSUE THREAD

**Issue by engram-design** [wearebraid/vue-formulate#153]
**Describe the bug**
This might be expected behaviour, and if so, disregard this.

My scenario is that I have a collection of fields for a form, spread out across tabs. I want to highlight which tab has a field with an error. I believe I can use `@validation` on the form (or an input) to determine whether an input has an error or not, and update the tab accordingly.

Refer to this [CodePen](https://codepen.io/crawf/pen/bGELqoM) for a cut-down example first.
 
When loading the pen, you'll notice it reports `firstName` as a field with an error - technically correct because it doesn't have a value. But as nothing has happened to the form to trigger validation, should this actually be fired? Likewise, when you edit the value of the field, its toggling an error status even though there's no error below the field shown (until you blur-off).

In practice, what this means for my case - demonstrated in [this Codepen](https://codepen.io/crawf/pen/LYGQWxp) is that tabs are shown with errors on-load. I can certainly get around this by detecting whether the form has been interacted with yet.

As one option - I'm wondering if its possible to provide a `errorShown` variable in the `error` payload for the `@validation` event? That way, we can check if there's an error - and if its shown. Then again, that may not be useful, as this event would be fired before the blur event.

I also believe this happens regardless of the `error-behavior` property being set.

**Comment by justin-schroeder** [comment]
I've actually thought about what the best way to validate a multi-step form is too. The problem with multi-step forms is there is absolutely no convention around how they are implemented so as a library we really just need to put the power into the developers hands to do it however they want. Now I'm not 100% sure I've landed on a good solution for it, so suggestions are welcome, but currently I think the best way would be to wrap each step or "tab" in your case it's own `group` and use `v-show` to hide/reveal. Then to assign a `ref` to each of those `group` inputs so you can programmatically access the instance. Then you can choose to check that validations state whenever you want for your own business logic.

```js
// whenever you want in your code...
const tabHasErrors = await this.$refs.tab1.hasValidationErrors()
// do whatever you want with that :)
```

I'd love to see this get more elegant over time, but I haven't seen a good proposal for an API on it yet.

**Comment by engram-design** [comment]
Good thinking with regards to a multi-step form, its not actually my specific use-case here (the tabs are in a modal, just to organise fields across a single form), but I think its still a related concern. In my case, there's a single `FormulateForm` element, with all tabs and fields being inside it.

Really, the question was about the behaviour of the `validation` event, and if possible to get some more context on whether the error is currently being shown, or triggered (or both). In an ideal world, adding a `isErrorShown` in addition to the `hasError` property would help fix this up.

By the way, superb work with all this. I've been putting all sorts of edge-cases, custom inputs and advanced behaviour, and its all feeling very solid. Much better than the roll-my-own solution with input components and Vuelidate. Great work 👍

**Comment by justin-schroeder** [comment]
Yeah as you've discovered here, the `validation` event does not contain information about the visibility of errors. Frankly — it probably wont in the future either. In fact it was debated whether or not it should when it was added to the library (it's on some "old" thread on here somewhere). The decision was made to leave that information out because this event is only supposed to fire when something about the current validation _state_ changes, and visibility of the errors is more of a presentational change. That said, I could see having another event like `@error-visibility` or something similar. That data is also available in the slot context.

I'm going to close this issue for now, but if you find your use case growing for that data feel free to open a feature request in the future with a proposed API for how you'd like to get that data considering it probably wont be included in the `validation` event itself, and hopefully we can make it happen 👍

**Comment by engram-design** [comment]
Yep, I think a separate `@error-visibility` event would be best - which is there for inputs, just not on the form.
