### ISSUE TITLE
Add the possibility to add links to error messages

### ISSUE THREAD

**Issue by jony1993** [wearebraid/vue-formulate#158]
Hi,

Often user need some more info how they can resolve an error.
Therefore it would be good, that we can add some links to detail info to the error messages.

Is there currently a way to add links (e.g. html link, router-link) to error messages?

**Comment by justin-schroeder** [comment]
Hi,

Currently there is no way to do this. We used to use a `v-html` for validation messages, but unfortunately its too big of a security risk since people can easily use the field `value` in their message leading to an XSS threat vector.

However, if it is very important you could allow it yourself by overriding the `errors` slot with a [slot component](https://vueformulate.com/guide/inputs/slots/#slot-components) that allows uses `v-html` instead, so while there is a path forward for your use case, this probably isn't a pattern that will be made "easily" available to the core library. Best of luck!
