### ISSUE TITLE
Trigger event on blur using schema form generation

### ISSUE THREAD

**Issue by LinnaeK** [wearebraid/vue-formulate#159]
We have recently been incorporating formulate into our application and absolutely love it. Thank you!

One question I had was regarding triggering events on blur when using a schema for the form generation. I have an API call I want to make after the user has entered a complete last name and date of birth. (To verify we don't have the user in the system already). I know it can be done with `@blur` using simple iteration, but haven't figured out how to trigger it with the schema. Is this feature already incorporated into schema generation or will it be incorporated in a future release?

**Comment by justin-schroeder** [comment]
Hi LinnaeK,

Glad you're enjoying it! I'll respond to two things since you provided the context:

1. Events in form schemas — This is not yet implemented but there is discussion happening over in #132 about how it will be implemented. In the meantime I believe you should be able to capture normal DOM bubbling events with the [`.native` modifier](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components) or worst case just using a `ref` to listen to bubbled events.

2. That said, your specific use case is a great example of when a [custom validation rule](https://vueformulate.com/guide/validation/#custom-validation-rules) would make sense. Custom validation rules are able to gather data from multiple inputs, and even perform an API request (they support async rules!). I would recommend you debounce your api call (optional of course), but other than that it should work almost perfectly for your exact use case.

I'll close this issue for now. If want to follow up about schema events let’s carry that on in #132. Best of luck 👍
