### ISSUE TITLE
Add class key to image preview (file input type)

### ISSUE THREAD

**Issue by hmaesta** [wearebraid/vue-formulate#172]
I believe we should add a `fileImagePreviewImg` referencing to the `<img>` image preview.

Real example:
→ https://codesandbox.io/s/vue-formulate-fileimage-used-220y3?file=/src/Formulate.vue

- My `uploadArea` has `h-10` (on Tailwind it's the same as `height: 2.5rem`)
- If the image has a height greater than `2.5rem`, it will overflow

To fix it I have to create a CSS class:

```css
.formulate-file-image-preview img {
  width: auto;
  height: 2.5rem;
}
```

It works fine, but I can't change my `uploadArea` height directly on `formulate-input` – or image preview will have a wrong height. 

For example, if I decrease the height, image will overflow:

```vue
<formulate-input type="image" :uploadArea="['h-8']" />
```

That would be fixed with:

```vue
<formulate-input type="image" :uploadArea="['h-8']" :fileImagePreviewImg="['h-6']" />
```

⚠️ Totally **not** a priority request. Should be the last one of the roadmap.

Workaround for Tailwind users:

```scss
.formulate-file-image-preview {
  &.h-10 img {
    @apply h-10;
  }
  &.h-12 img {
    @apply h-12;
  }
  &.h-20 img {
    @apply h-20;
  }

  img {
    @apply w-auto;
  }
}
```

**Comment by justin-schroeder** [comment]
Good idea! I might not get to this super soon, but it shouldn't be too hard to submit as a PR to the `release/2.4.3` branch. I'm not a tailwind user myself so I sometimes forget how important it is that literally every element be classed.

There's also a test case in that you can just modify slightly to make sure the class is being assigned properly. The logic for these classes is in https://github.com/wearebraid/vue-formulate/blob/master/src/libs/classes.js

Since that `<img>` doesn't include a class by default you might have to add a small bit of logic to line 63 (https://github.com/wearebraid/vue-formulate/blob/master/src/libs/classes.js#L63). The `input` element element there also does not have any default classes so you’ll want to do the same thing for this new class key (return an empty array). Maybe something like `['input', 'file-image-preview-img`].includes(key)`

**Comment by justin-schroeder** [comment]
Ok, this has been added in `release/2.5.0` as class key `fileImagePreviewImage` 👍
