### ISSUE TITLE
Add @repeatableAdded and @repeatableRemoved events to `group` input types

### ISSUE THREAD

**Issue by codekiln** [wearebraid/vue-formulate#183]
In `v2.4.3`, when inside of a repeatable group, clicking on the button to add another element does not currently transition the focus to the first input inside the added group. This would be a nice feature to have. 

Example: [Vue Formulate Nested Groups 2](https://codesandbox.io/s/vue-formulate-nested-groups-2-m18ff?file=/src/components/MinMaxGroup.vue), click on the add button, note that focus doesn't immediately move to first input in next group.

**Comment by justin-schroeder** [comment]
I could see this being a really nice feature. I do have some concerns about it being something that is enabled by default, since forms could have their "repeatables" added programmatically instead of through the button click, and in those instances people may or may not want to focus. What if we left this in user land but provided new events `@repeatableAdded` and `@repeatableRemoved`. We could even ensure these events are called after `nextTick` to ensure the DOM has been rendered. Opinions?

**Comment by codekiln** [comment]
> forms could have their "repeatables" added programmatically instead of through the button click, and in those instances people may or may not want to focus

Great point.

> What if we left this in user land but provided new events

That sounds sensible to me!

**Comment by Fealthas** [comment]
Not sure if this is related, but removing an item from a repeatable group does not emit a 'changed' or 'input' event. (or any event at all??? not sure.)

I assume that adding the two new events would fix this as well.

**Comment by justin-schroeder** [comment]
@codekiln These events are now implemented in the `release/2.5.0` branch as `@repeatableAdded` and `@repeatableRemoved` 👍

**Comment by joekaldas** [comment]
> @codekiln These events are now implemented in the `release/2.5.0` branch as `@repeatableAdded` and `@repeatableRemoved` 👍

About this, is there any `@repeatBeforeRemove` or `@repeatAfterAdded` kind of events?
I want to remove the repeatable for example after sending the backend for deletion.
