### ISSUE TITLE
:placeholder & :disabled props allow truthy/falsy values rather than strictly Boolean

### ISSUE THREAD

**Issue by titusdecali** [wearebraid/vue-formulate#195]
**Describe the new feature you'd like**
I would like to bind my :placeholder display logic to whether or not a data value is truthy or false. Currently for the logic below to work, otherSelectValue must return a Boolean.

```
            :placeholder="
              otherSelectValue
                ? 'make a choice'
                : 'choose otherSelectValue first please'
            "
```

If truthy/falsy values could be used for both `:placeholder` and `:disabled`, we could easily force users to select values in a specific order (I'm using this on a cascade series of select inputs), and both disable or display a placeholder (guide) message based on other input values.

**Comment by justin-schroeder** [comment]
Hey @titusdecali.

I'm a bit confused about what you mean by `otherSelectedValue` needing to be a strict boolean? Everything inside the a `v-bind` is just a normal javascript expression so that's nothing specific to our library. My guess is that you're using something like a zero `0` value and trying to determine if that's truthy or falsey perhaps? In that case be ware that all HTML inputs represent numbers as a `String` not a `number` even if your original value was a `Number`. So while `0` is falsey that zero might actually be `"0"` which is truthy.

The only place im aware of strict `boolean` checking on attributes is if an attribute should be rendered or not. In order to _not_ render an attribute defined in a template it's value must be strictly boolean `false`:

```vue
<FormulateInput :data-hello="false" />
```

But that's just how Vue works, nothing about this library.

Is this helpful 🤷‍♂️?

**Comment by titusdecali** [comment]
It does work fine as you say in a sandbox:
https://codesandbox.io/s/vue-formulate-reproduction-template-8evwj?file=/src/components/Reproduction.vue

Looking deeper, this is a result of me using objects instead of arrays as you mentioned in my other bug report.
It doesn't throw an error if you use objects, but for cases like this (and many others) it causes issue that are not easily identifiable.

If we had a `mode="`object"` prop I would have saved 3 days of troubleshooting various issues.
Really, really looking forward to that feature.
