### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by henrikromby** [wearebraid/vue-formulate#2]
Hello! First of all, its a really cool project you’ve got here. It’s something I’ve been trying to do myself for a really long time with little success.

Is it possible to do server side validation and pass in the error messages for each field after form submission?

**Comment by justin-schroeder** [comment]
@henrikromby Thanks! Yes and no. Currently you can pass backend validation on a per-input basis using the `:error` or `:errors` props. Something like this:

```vue
<FormulateInput
  ...
  :errors="formErrors[fieldName]"
/>
```

But it’s on the short list to add form-wide error hydration, as well as a behavior for how/when to show and hide those (like should backend validation errors go away when someone starts typing – maybe, but it depends and that power should be in the user’s hands).

It’s worth leaving this open though since it's a solid feature request.

**Comment by justin-schroeder** [comment]
@henrikromby this feature and much more was added in version 2.2.0. Thanks for the great suggestion!

https://vueformulate.com/guide/forms/error-handling
