### ISSUE TITLE
`context.model` is undefined when using a custom slot for `#element`

### ISSUE THREAD

**Issue by hacknug** [wearebraid/vue-formulate#217]
**Describe the bug**
Not sure I'm doing something wrong or not but `context.model` is undefined when trying to use slots to customize the input's markup.

**To Reproduce**
Open demo link and see how using a custom slot breaks up the binding.

**Reproduction**
https://codepen.io/hack_nug/pen/MWyWgKm

**Expected behavior**
`context.model` should be available so we can build custom stuff.

**Comment by justin-schroeder** [comment]
Thanks for the reproduction of the issue — you're right, it's somehow loosing its `model` property when transitioning through `FormulateSlot`. I'll mark this as a bug. In the meantime, using a `slotComponent` should allow you to successfully use it as a prop instead.

**Comment by justin-schroeder** [comment]
Thanks for the report 👍 This is fixed in the `release/2.4.4` branch (not yet released as of this comment).

However, of note @hacknug your example uses the `element` slot for your to add an input which was great for reproduction purposes, but I wanted to note that it would be preferable to use a [custom input for that kind of which has a slightly different registration process](https://vueformulate.com/guide/inputs/custom-inputs/#registering-an-input).

**Comment by hacknug** [comment]
@justin-schroeder yeah, I ended up using `slotComponent` like you suggested. Thank you again for your work!
