### ISSUE TITLE
Add IsValid event to FormulateForm component

### ISSUE THREAD

**Issue by Zysce** [wearebraid/vue-formulate#228]
**Describe the new feature you'd like**
```
<FormulateForm
      @is-valid="formIsValid"
    />
```

It would return true if no error and false if any field is in error state.
This event is fired based on validation change.

I see that the FormulateForm has the method hasValidationErrors method from the registry.
Would it be possible to return the promise from this method?

**Why do I need this?**
I have a stepper and I would like to disable the next button when the form is invalid.
Right now, it is not easily feasible for me.
I watch the event validation but it is per field so I need to consolidate every validation to get the actual error status of the whole form.
(great job btw, this library rocks :) )

**Comment by justin-schroeder** [comment]
Howdy 👋

## Today:

Other than the `@validation` event, you can also manually request validation information about your form. It's not super elegant (see future implementation), but it works. Here's an example:

https://codepen.io/justin-schroeder/pen/KKzaqjJ

## Future:

We're planning to add a default scoped slot to the `<FormulateForm>` component with context information (see #127) including things like `hasErrors`, or perhaps `isValid`. The usage would be similar to what you're indicating, although it would be more declarative rather than event based:

```vue
<FormulateForm
  #default="{ hasErrors }"
>
  <FormulateInput
    type="button"
    :disabled="hasErrors"
  />
</FormulateForm>
```

Currently that's slated for `v2.5` although I don't have specific progress to report on it.

**Comment by skyf0xx** [comment]
Is it possible to add this pattern to the docs? Quite hard to find

**Comment by justin-schroeder** [comment]
Well..its possible but not "supported" today. Once we have proper form context objects working we'll be sure to fully document it. Track #127 for updates.
