### ISSUE TITLE
Reducing file size - Remove optional/unused features

### ISSUE THREAD

**Issue by willans** [wearebraid/vue-formulate#246]
Currently trialing the use of Formulate. However, out of the box, when minified, it's adding roughly 75-100kb to the build.

Is there any ability to turn off features/parts of Vue Formulate? e.g. turn off date inputs, file inputs, repeaters etc.

**Comment by justin-schroeder** [comment]
As of today, the ESM is 65.7kb raw. We are very careful to watch that the build size does not inflate much, but we care way more about the gzip size which is currently 16Kb.

That 16Kb gzipped bundle will probably always be roughly that size, but the ecosystem will grow around it. For example, i18n is broken out into its own package to support better tree shaking, and as more plugins are developed over time that trend will continue. The existing set of components could be *slightly* reduced by tree shaking the inputs themselves, but those components are already quite small, and most of the bulk is in the logic files and context objects themselves.

I guess what I'm saying is — I hear you — performance and size is really important to me, and I'm committed to not seeing the package grow substantially, you might even see slight improvements over time on the 16Kb gzip payload. Buuuuuut....it isn't currently a high priority since 16kb gzip is roughly the same weight as one of those mini avatars of our faces on these comments and the payoff of having all the importing done for most users helps us live up to the tagline (easiest way to build forms with vue) a little better.

That said, track Issue #190. Depending on how that's implemented you *might* get your wish :)
