### ISSUE TITLE
Redundant fields for a file field?

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#248]
The values ​​in the form model contain significantly more parameters than the object in the ```@submit``` event

Does it need parameters like ```context``` and ```options```?

### CodePen:
[https://codepen.io/maksabuzyarov/pen/rNevRvQ](https://codepen.io/maksabuzyarov/pen/rNevRvQ)

**Expected behavior**
I expected same data in the model and values from submit event

**Device information:**
 - Browser Google Chrome 
 - Version 2.4.3

**Comment by justin-schroeder** [comment]
It does yes. Files are complex little beasts, and to smooth out the experience vue-formulate wraps files in an instance of [`FileUpload`](https://github.com/wearebraid/vue-formulate/blob/master/src/FileUpload.js). This allows us to hold on (and v-model) the native [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList). When you output your `v-model` values it looks very complex because the stringifier is printing the entire instance of the FileUpload which has back references to context and what not.

But to answer your question — yes it's necessary, but once you know it's an instance of FileUpload it should make working with it much easier (you can manually upload the file when you want etc). Does that explanation help clear it up at all? I was actually talking to someone about this today and how we need to improve the docs around this exact issue.

**Comment by justin-schroeder** [comment]
Ok, docs in 2.5 will be improved, and include a full control-flow diagram for file uploads on form submission. Preview here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/file/#file-2
