### ISSUE TITLE
Interaction of schema-generated form elements and custom components

### ISSUE THREAD

**Issue by ahndohun** [wearebraid/vue-formulate#249]
I want to make the form element created with the schema and the custom component (eg address finder) interact. Is it possible?

**Comment by justin-schroeder** [comment]
It is possible, but you'll need to mutate the schema to interact with the elements. Since JSON doesn't support expressions, and schemas should be backwards compatible with JSON, we do not support conditionals directly via the schema. The recommended approach would be to use a computed property to return your schema array, and then use that computed property to mutate the schema itself (which is reactive).
