### ISSUE TITLE
Disable slot components at type level

### ISSUE THREAD

**Issue by willans** [wearebraid/vue-formulate#254]
I'm adding a custom checkbox component, in which the a label wraps the checkbox and the label text (which is at this point a span).

Roughly along the lines of

```
<template>
    <label
        class="flex items-start"
        :disabled="$props.context.attributes.disabled"
        :for="$props.context.id"
    >
        <input
            v-model="$props.context.model"
            v-bind="$props.context.attributes"
            :value="$props.context.value"
            :type="$props.context.type"
            class="sr-only"
            @focus="$data.hasKeyboardFocus = isKeyboard()"
            @blur="$data.hasKeyboardFocus = false"
        >

        <span>CUSTOM FANCY CHECKOX</span>

        <span
            class="leading-normal self-center"
            v-html="$props.context.label"
        />
    </label>
</template>
```

Is there any way to disable slot components, particularly for specific types. Something along the lines of:

```
Vue.use(VueFormulate, {
    library: {
        // the `type` of input you’re targeting.
        file: {
            slotComponents: {
                label: false
            }
        }
    }
})
```

I don't want to replace the entire component, as I'd still like to utilise the other slots like help and validation-messages.

I could just add a `hidden` class to the duplicate label, but I'd rather just have it removed from the markup entirely.

**Comment by justin-schroeder** [comment]
I'd suggest just defining a component with a render function that returns null, maybe like `NullSlotComponent`:

```js
<script>
export default {
  render () {
    return null
  }
}
</script>
```

Good idea to allow `false` to disable a slot all together, however in the future I think we're going to use a component `stack` to describe how components are layered together (to remove a slot component you would just leave it out of the stack). You can find/track that issue here #129. I'll close this issue in favor of that solution.
