### ISSUE TITLE
Unexpected behaviour of radiobox with boolean values

### ISSUE THREAD

**Issue by last-partizan** [wearebraid/vue-formulate#266]
**Describe the bug**
Radio input behaves strangely when used with boolean values.

**To Reproduce**

Just open this codepen and click False, True, False.

https://codepen.io/last-partizan/pen/xxVNyMY

If default is `false`, corresponding radio is not checked.
After click on False, it becomes checked.
After click on True, it becomes checked and value is `(boolean)true`
After click on False, it becomes checked and value is `(string)""`

**Expected behavior**
It returns expected values.
Corresponding radio is checked when value default is false.

**Comment by justin-schroeder** [comment]
@last-partizan yeah unfortunately this is actually expected. HTML inputs do not allow for non-string values. Vue tries to coerce some semblance of functionality out of them so it kinda works for the initial value but not anything else. You'll find this erratic functionality with integers as well. The only time where booleans genuinely do work is _single_ checkboxes:

```vue
<FormulateInput
  type="checkbox"
  name="example"
/>
```

That's because behind the scenes the HTML either adds or removes that input which is effectively a boolean, so Vue automatically does this coercion properly. I suppose we could do some kind of custom logic to check all the different values in an option list to see if they are all booleans and do some kind of model masking to allow this functionality, but it seems a bit expensive. Open to suggestions though.

When we release a Vue 3 version, we'll be able to define our own model modifiers, so we could do something like:

```vue
<FormulateInput
  type="checkbox"
  :options="options" // assume these options have boolean values
  v-model.boolean="value"
/>
```

Until then either use a checkbox, or use custom getters/setters to manipulate the model value.

**Comment by last-partizan** [comment]
Thanks.

For now i'll use strings.

This issue should be closed probably, as it doesn't relates to VueFormulate directly.
