### ISSUE TITLE
FormulateForm not emitting when context.model changes in custom plugin

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#298]
**Description**
Created a simple plugin for Find&Replace but for some reason the context.model is not emitted as expected. 

**To Reproduce**
1 Import the plugin
  import keys from '..//components//vue-formulate//keys'
  Vue.component('keys', keys)
  keys: { classification: 'text', component: 'keys' }, 
2 Add value propertie 
  context: {type: Object, required: true}
3 Add the style to the template
  :class="`formulate-input-element formulate-input-element--${context.type}`"
  :data-type="context.type"
4 Add the model to the template
  context.model (v-model)
  v-bind="context.attributes"
  @blur="context.blurHandler"
  context.rootEmit("input", this.context.model) 
5 Call the plugin
`  <FormulateInput type="keys" v-model="array" />`
  Whereby array is for example:
    [
        { find: "a", replace: "b" },
        { find: 3, replace: 5 },
    ]

### CodeSandbox
https://codesandbox.io/s/z11qg

**Expected behavior**
Expected the plugin would emit the scheme data after a change in **context.model** (just like normal inputs and the autocomplete plugin)
![image](https://user-images.githubusercontent.com/25219229/97106651-5676eb80-16c3-11eb-840a-ca8550c936ca.png)
But nothing happens with my little Find&Replace plugin
![image](https://user-images.githubusercontent.com/25219229/97106711-8b833e00-16c3-11eb-8488-6d2c0ad7671f.png)
After adding **this.context.rootEmit("input", this.context.model)** only FormulateInput emits
![image](https://user-images.githubusercontent.com/25219229/97106797-e61c9a00-16c3-11eb-82ea-a1fea087b424.png)

**Comment by justin-schroeder** [comment]
You should not `rootEmit('input')` since the `input` event is used for v-modeling. The `input` event is automatically emitted from mutations to `context.model`.

I wasnt able to quite follow along the reproduction on code sandbox. Immediately apparent though was a JS error in the console, so might be worth looking into that too.

**Comment by Rednas83** [comment]
I removed the error and also the rootemit as suggested, but still the **context.model** is not emitting anything
https://z11qg.csb.app/
Only the warnings for not mutating props are sill remaining (similar in the autocomplete example)
![image](https://user-images.githubusercontent.com/25219229/97224653-beb3f300-17d1-11eb-92eb-41a78eaee04b.png)

Is it possible for you to investigate? Because I can't see any difference with the autocomplete and I am not sure what I can try further

**Comment by justin-schroeder** [comment]
ok I took a look. First off, you cannot v-model sub-properties of an array in context since there is no listener there. In your loop you are v-modeling `item.find` and `item.replace` — you cannot do that since there are no getters/setters defined for those properties. Your component needs set the value of `context.model` in it's entirety something like:

`context.model = [...items]`

This works fine when doing a `v-model` on `context.model` for normal inputs because internally when you v-model vue does:

```vue
// This:
<input v-model="context.model">
// Is the same as:
<input
  @input="context.model = $event"
  :value="context.model"
>
```

So you can see you're setting the value of `context.model`. Also, side note, due to how `v-model` works, you really should not do a `v-model` and an `@input` listener on the same `<input>`. So it is absolutely possible to do what you're trying to do, you just need to make mutations trigger a full set for the `context.model`

**Comment by Rednas83** [comment]
Thanx Justin for this solution. I also updated the Sandbox with your solution
https://z11qg.csb.app/

But it seems FormulateInput is not emitting
![image](https://user-images.githubusercontent.com/25219229/97361628-17ea5800-18a0-11eb-8fc5-f442fd246ab0.png)

It is emitting for normal inputs and also for autocomplete
![image](https://user-images.githubusercontent.com/25219229/97361480-e1acd880-189f-11eb-9878-ac4721fda562.png)

This is causing a bug in my wrapper component for vueformulate.

Any idea why FormulateInput is not emitting?
