### ISSUE TITLE
<FormulateInput> emits input only once when type=select

### ISSUE THREAD

**Issue by ludo237** [wearebraid/vue-formulate#318]
**Describe the bug**
When using `<FormulateInput type="select">` the componet emits the input event only once

**To Reproduce**
1. Go to the Codesanbox fork
2. Use the FormulateInput select component
3. See error

**Reproduction**
Reproduction link on Codesanbox:

https://codesandbox.io/s/vue-formulate-bugs-on-formulateinput-type-select-qt2xe?file=/src/components/Reproduction.vue:29-33

**Expected behavior**
Every time the selected option changes an event should be emitted by the input itself

**Device information:**
 - Device: Desktop PC
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version Latest stable

**Comment by justin-schroeder** [comment]
Yeah, this is an easy trap to fall into. The issue is you are using `Number` values as values for the select list which leads to unpredictable behavior since integers are not supported in HTML. Cast to string keys and all is well:

https://codesandbox.io/s/vue-formulate-bugs-on-formulateinput-type-select-forked-bkpch?file=/src/components/Reproduction.vue

There is a note in the docs for this, but its a fairly common gotchya since often the `value` is a database `id`.

![image](https://user-images.githubusercontent.com/1950463/99548193-5dbdac00-2986-11eb-980a-c73b91349227.png)

**Comment by ludo237** [comment]
@justin-schroeder and I read the doc twice... shame on me! 

Thanks for the fast reply, sorry for the time waste
