### ISSUE TITLE
Selected value does not update after first selection when using computed property array

### ISSUE THREAD

**Issue by crisclacerda** [wearebraid/vue-formulate#331]
**Describe the bug**
Selected value does not update after first selection when using computed property array

**To Reproduce**
1. Go to https://codepen.io/skarface00/pen/BaLKWdX
2. Click on whatever label
3. Corrected value is chosen
4. Click on other label
5. Value from step '3' is still chosen instead of the new one

**Comment by justin-schroeder** [comment]
This is due to using integer values. Unfortunately HTML only supports string keys. There are a half dozen of these issues that have been filed, so it's definitely a common sticking point. 

https://github.com/wearebraid/vue-formulate/issues/318

The good news is it's easy to fix in your code:

https://codepen.io/justin-schroeder/pen/dypMVBG

**Comment by crisclacerda** [comment]
Awesome, thanks!
Maybe worth adding a comment about it in the docs?

**Comment by justin-schroeder** [comment]
It's there :)


![image](https://user-images.githubusercontent.com/1950463/101271426-8c8e9d00-3750-11eb-81d3-19237bc1f6a3.png)
