### ISSUE TITLE
Accepted validation error msg not appears on iOS Safari

### ISSUE THREAD

**Issue by erkage** [wearebraid/vue-formulate#340]
**Describe the bug**
Using accepted validation on a checkbox the error msg not appears on Apple iPhone/iPad in Safari and Chrome.
Required is also not working on checkbox input.

**To Reproduce**
1. Go to https://vueformulate.com/guide/validation/#available-rules
2. Click on "Accepted"
3. Click twice on the checkbox or the label "i accept the terms of service?"
4. On dekstop it shows "Please accept the terms." on iOS Safari nothing.

**Expected behavior**
Show validation error msg.

**Device information:**
 - Device: iPhone 11 Pro, iPad Air 2
 - OS: iOS 14.3, iPadOS 14.3
 - Browser: Safari and Chrome (87.0.4280.77)

**Comment by justin-schroeder** [comment]
I believe this has to do with the blur event on ios not getting triggered. If you placed one of these inputs inside a form and tried to submit it, i believe the error would still show and it would not trigger the submit event, or if you set the `error-behavior` to `live` I think you would get the same effect.

Not sure if this should be classified as a bug or not since its more about how iOS handles "blur" on a touch device and it only relates to the visibility of the error not the state of the error. Open to thoughts 🤷‍♂️

**Comment by justin-schroeder** [comment]
This one will not be fixed since there is no blur event on ios.
