### ISSUE TITLE
Data is not updated correctly when groups are rendered using v-for based on the results of a checkbox

### ISSUE THREAD

**Issue by dreamofi** [wearebraid/vue-formulate#349]
**Describe the bug**
Data is not updated correctly when groups are rendered using v-for based on the results of a checkbox

**To Reproduce**
1. I have a select box named "Dataset", a checkbox named "Tables"
2. When I select an option in "Dataset", "Tables" will display the tables related to the selected option in "Dataset".
3. Based on the selected options in "Tables", I intended to use "v-for" to render multiple groups (named "Parameters") which also containing multiple inputs (but the only purpose is to display the values selected in "Tables")
4. At the beginning, if I only check some options in "Tables", the data are reflected correctly. However, if I select more than 2 or more options, and then uncheck one, the data on the form is not updated correctly.

**Reproduction**
https://codepen.io/dreamofi/pen/qBaxbpR

**Expected behavior**
The data is updated correctly

**Screenshots**
![VueFormulateBugScreenshot](https://user-images.githubusercontent.com/19624744/103351909-43bfcf00-4ad7-11eb-9174-8b37a4ebec68.jpg)

**Device information:**
 - Device: PC
 - OS: Windows 10, Linux (Debian 10)
 - Browser: Firefox latest, Chrome latest

**Comment by justin-schroeder** [comment]
Thanks for the great reproduction and screenshots @dreamofi! So a few things are going on here that are causing this strange behavior, but they all relate to the mounting and un-mounting of components from the registry. The primary issue is that when a `FormulateInput` is unmounted, it removes its data from the DOM. In 90% of cases this makes a ton of sense, but in some can have some odd side effects, mostly when it doesn't seem something is mounting and un-mounting. Technically, the fields inside that first group are being unmounted and re-mounted when you make mutations to the root object leading to that unexpected data loss.

```
// These are all technically the same
{
  parameters: []
}
{
  parameters: null
}
{
 parameters: [
   {
    "key_t22": [
      {}
    ]
 ]
```

Another thing to note is that the above are all [technically empty](https://github.com/wearebraid/vue-formulate/blob/master/src/libs/utils.js#L311-L327) since they never recursively have a value. So one solution to you problem is to be ok with there being "empty" (our definition) `parameters` and just "fix" incorrect/weird data-reset that is happening. You can accomplish that by adding `:keep-model-data="true"` on your second group:

https://codepen.io/justin-schroeder/pen/vYXjYQY

However, to be honest, using multiple v-for loops to render multiple nested `groups` seems like asking for trouble either way, it's essentially that means the inputs are essentially 4 loops deep, since each group represents its own loop too. 

Now, I don't know what you're _actually_ building, but personally I think this could probably be done with a single `group` and no v-for's at all. One of my favorite patterns to use is having the `#default` slot of a group contain it's own component with whatever FormulateInput's you like in it wrapped only in a div, no need for any other formulate wrappers since the values will properly propagate up to the group. So something like:

```vue
<FormulateForm
  v-model="formValues"
>
    <FormulateInput
      type="select"
      label="dataset"
      name="dataset"
      :options="datasetList"
    />
  <FormulateInput
    type="group"
    name="parameters"
    #default="{ index }"
  >
    <TableInputs :type="dataset[index]" />
  </FormulateInput>
</FormulateForm>
```

That makes it easy to put any logic you want inside `TableInputs.vue` and let it have it's own scope so you can use data properties and what not.

As for if this is a bug or not...its on the fence. I 100% agree it is very unintuitive why that data is disappearing, but "fixing" it would introduce other unintuitive behaviors. I'll keep stewing on it.

**Comment by dreamofi** [comment]
@justin-schroeder 	
Thank you for your reply! What I want to build is a complex form with lots of nested and conditional groups (those that are only showed based on the values in other fields), and then display the JSON exactly like how the form is structured (similar to this site [https://k8syaml.com/](https://k8syaml.com/)). That's also the reason why I decided to use v-for with type='group', and that I don't know any other ways.

Prior to using Vue Formulate, I tried nchForm to generate form from a JSON schema, and it kinda works, but its performance and handling of conditional display are really subpar.

When I tried Vue Formulate, initially I also aimed to use its form generation from JSON, but once again whenever nested groups and conditional display are involved, things started getting complicated. So you can see that in my codepen, I switched to a more "basic" approach of using Vue Formulate.

Unfortunately, I was unable to tried your suggestion, partly because I was still confused about the default slot pattern and whether I'm supposed to create a custom input. My project use Element UI framework, so finally I decided to use its form components to manually recreate the form :(.
