### ISSUE TITLE
Input doesn't update on Form v-model assignment

### ISSUE THREAD

**Issue by j-manu** [wearebraid/vue-formulate#357]
**Describe the bug**

With `FormulateForm v-model="values"` any assignment to `values.prop` should update the corresponding `FormInput`.
Assigning a value works but updating a value does not.

**To Reproduce**
https://codesandbox.io/s/vue-formulate-reproduction-template-forked-l9ooo?file=/src/App.vue

* Select two dates
* Everything works as expected - 
![image](https://user-images.githubusercontent.com/72501/103987282-42b32f80-51b2-11eb-97af-302c5e32de7f.png)

* Change one the dates
* ![image](https://user-images.githubusercontent.com/72501/103987184-13042780-51b2-11eb-9f96-0ec4c898ae8c.png)
* The object updates but the input doesn't

**Expected behavior**
`v-model` value and FormInput value should always be in sync

**Comment by justin-schroeder** [comment]
Ok, so 2 things to note on your example:

1. Its generally not a good idea to mutate the object you are watching in the watcher itself as it can easily lead to oodles of watch events or even infinite loops.
2. The reason your input is not updating is because it is setting a (type) `Number` on an `<input type="number">` which is not supported in HTML. HTML only supports string values. Vue "kinda" fixes this by coercing the value to a string the first pass, but doesnt do it on subsequent ones. To fix your example, just cast your value to a string before assigning it to the model.

In your watcher:

```js
this.values.date_difference = String(this.date_diff_calculate());
```

That should get it all working for ya. Good luck 👍

**Comment by j-manu** [comment]
Thank you!!

I know watch is not ideal but nothing else worked.

```
<FormulateInput
                name="date_difference"
                :value="date_diff_calculate()"
                type="number"
                label="Difference"
              />
```

where `date_diff_calculate()` is a function or

```
<FormulateInput
                name="date_difference"
                :value="date_diff_calculate"
                type="number"
                label="Difference"
              />
```
where `date_diff_calculate` is computed didn't work.

For the benefit of anyone who stumbles upon this, I solved this by adding a `v-model` to the watched inputs, watching that instead of `values` and setting the dependent input.

Complete example - https://codesandbox.io/s/vue-formulate-reproduction-template-forked-0uw2f?file=/src/App.vue

Is there a more idiomatic way of doing this?
