### ISSUE TITLE
Cannot dynamically assign name to a form in route change 

### ISSUE THREAD

**Issue by miguelcarrillo** [wearebraid/vue-formulate#360]
I'm using vue-formulate in a master-detail structure, with vue-router nested routes. 

The children are the same component and use the same FormulateForm component, changing the values (and model).

In addition, I'm submitting from an outside button, using the name of the form and `this.$formulate.submit(this.myForm);`

If I use the dynamic `:name` prop for the Form, and change the name on route change (watching the route, as is the same Child component with different ids) the reference to the FormulateForm is lost, and get these error messages (in the CodeSandbox example), when I try to submit:

`evaluate/Xt.prototype.submit@https://9o7qw.csb.app/node_modules/@braid/vue-formulate/dist/formulate.esm.js:2868:17`

`[Vue warn]: Error in v-on handler: "TypeError: this.registry.get(...) is undefined"`

BTW, if I simply give a static name to the FormulateForm component (the simplest solution) I have cases where the reference is also lost, when route changes. But I think this bug is more reproducible and important, because the issue is with assigning the name.

**Reproduction**
https://codesandbox.io/s/vue-formulate-with-vue-router-nested-routes-9o7qw?file=/src/views/Child.vue:60-73

Thanks!

**Comment by justin-schroeder** [comment]
@miguelcarrillo cool form idea. The code you have is very close to working, the only issue is the re-use of the `<FormulateForm>` since the form is never un-bound (vue is preserving the instance) it never fully registers. This is common with repeatables and dynamic swapping. No problem though, just put a `:key` prop on the `FormulateForm`. That will resolve the registration issue. The only other challenge is getting your values to hydrate properly on route change. In theory this would work immediately, but again, because of the late binding of the form you'll need to use a `nextTick`:

```js
    this.$nextTick(() => {
      this.values = data.fecthItem(this.id);
    });
```

I think that should make it all work. Here's a forked example with those changes:

https://codesandbox.io/s/vue-formulate-with-vue-router-nested-routes-forked-cbce7?file=/src/views/Child.vue

**Comment by miguelcarrillo** [comment]
Thanks a lot for the swift response, you´re a life saver. Worked both in the sandbox and in the actual project.

I just want to share the solution I recently found for my particular problem: In the FormulateForm add a submit input, not visible

```javascript
    <FormulateForm
      name="myForm"
      @submit="onSubmit"
      :schema="schema"
      v-model="model"
      :errors="inputErrors"
    >
      <FormulateInput
        type="submit"
        id="submit-form"
        class="d-none"
      >
      </FormulateInput>
    </FormulateForm>
```

Then outside I create a label for the button, styled as a button:

```javascript
    <label
      for="submit-form"
      tabindex="0"
      class="btn btn-primary mb-0"
      :disabled="formstate.hasErrors"
    >
      Submit
    </label>
```

But it feels more of a hack. Thanks again and thanks for a great library. I just wrapped vue-select and element ui inputs with vue-formulate and they worked like a charm!

**Comment by justin-schroeder** [comment]
Awesome work!
