### ISSUE TITLE
Multi-Select Warning when using variables to set options

### ISSUE THREAD

**Issue by j-manu** [wearebraid/vue-formulate#363]
**Describe the bug**
Vue gives a warning `<select multiple v-model="context.model"> expects an Array value for its binding, but got String` when using variable to set the options of select when multi select is enabled.

**To Reproduce**
https://codesandbox.io/s/vue-formulate-reproduction-template-forked-ruvlq?file=/src/components/Reproduction.vue

The warning is logged to the console.
1st select is multi, options are set inline - No warning
2nd select is single, options are set using variable - No warning
3rd select is multi, same options variable as 2nd - Warning

**Expected behavior**
Adding `multiple` shouldn't trigger any warning.

**Comment by justin-schroeder** [comment]
Yep, thanks for the report!

**Comment by justin-schroeder** [comment]
@j-manu this took a while to track down — this only occurs if you use a placeholder on a `select` with `multiple` since there is no _real world_ way to do a placeholder on a multiple it fell through the cracks. I'm actually going to close this as a `wontfix` since its outside of normal use case and I dont want to add additional weight to the bundle for that. Thanks for the report though!

**Comment by j-manu** [comment]
@justin-schroeder Thank you for tracking this down. Can vue-formulate show a better error in this case? "invalid option placeholder for multiple select" ?

**Comment by justin-schroeder** [comment]
@j-manu not at the moment — currently we don't have a development-only build so we haven't included developer error messages. It might be something to consider for v3 though.
