### ISSUE TITLE
Error Behavior only "submit" not respecting after the first error fired

### ISSUE THREAD

**Issue by vicenterusso** [wearebraid/vue-formulate#376]
**Describe the bug**
Error Behavior "submit" not respecting after the first error fired

**To Reproduce**
1. Go to https://codepen.io/vicenterusso/pen/Rworowj
2. Type less than 5 characters and hit submit.
3. After the error appears, the form starts to track errors "live".. it seems

**Expected behavior**
The form should respect error-behavior after the first error is triggered

**Comment by justin-schroeder** [comment]
Not a bug, this is working as intended. It's annoying UX to show validation errors that only go away when you try to submit again. Open to suggestions if there is a good ux you're looking for here that isn't supported though.

**Comment by vicenterusso** [comment]
> Not a bug, this is working as intended. It's annoying UX to show validation errors that only go away when you try to submit again. Open to suggestions if there is a good ux you're looking for here that isn't supported though.

Maybe I didn't make myself clear. The problem I see is not the error disappearing when user change the input _**after**_ the error appears (when click submit). The error should disappear.

But the error message should not be displayed again (any error/validation rule) when user is typing, because there is an explicit `"error-behavior": "submit"`.

Why change the behaviour after hit submit?

**Comment by justin-schroeder** [comment]
I hear you amigo. The opinionated UX decision here is that after someone tries to submit a form with invalid fields, we should show why the fields are invalid until they have resolved the issue — so that is what happens. The other distinction is not actually all that clear either. Do you show errors when they hit submit and just "lock" those in until they hit submit again? Do you show them only till they start typing some values in? Do you show them until they are resolved (which is what live mode is). Etc etc. I'd love to hear your UX opinion on how you were hoping to handle failing validation errors on submit.

**Comment by vicenterusso** [comment]
Thanks for your reply

This is what _should happen in my opinion_ when error-behavior is set to **submit**

1) user enters a failing input (no error displayed) **works**
2) user hits submit (error is displayed) **works**
3) user changes the input (error message gone) **works**
4) *no error being displayed again until user hits submit another time* - not working. from this point it turns to live mode. It should not display any other error until user hits submit again

As I understand, today we have a mix: "not live" until the first submit hit, and full "live" after

**Comment by justin-schroeder** [comment]
Gotchya, so roughly the algo is:

- On submit with failures.
- Each input shows any validation errors.
- Each input remember which rules caused the submit failure.
- On edit only show errors related to that failing validation member (since another one could fail during the edit we wouldn't want to show that since it's not "live").
- Once the failing rule is resolved — then remember that that validation rule was resolved so don't display errors again until re-submission (since a user could edit it again and re-cause a failing state)

Seems complicated, but Id be happy to implement it if I was sure it was a good UX. I'm not convinced it is. Here's my user story:

When someone submits a form and it fails due to validation — they are frustrated and want to fix the validation errors so they can submit the form — thus we should _all_ outstanding validation issues that are required to successfully submit the form. "Hiding" any invalid values at this point would subject a user to playing "whackamole": submitting, fix error, submit, fix error etc.

I'm still open to persuasion though, so perhaps a few real world examples of how "switching" to live mode (which, you're correct, is what happens) causes a poorer user experience might help me understand? Thanks!

**Comment by vicenterusso** [comment]
Well, I am now convinced that the current behavior is a better UX based on the "remember rule" + whackamole 😄

Thanks for your time
