### ISSUE TITLE
Cannot pass an object as a prop to a custom component

### ISSUE THREAD

**Issue by abrin** [wearebraid/vue-formulate#407]
**Describe the bug**

I've been trying to implement a custom input that is passed a configuration object as a prop. But, it appears that passing an object  (it seems to work with an array, string, boolean, number, etc)...  I followed the [instructions](https://vueformulate.com/guide/inputs/custom-inputs/#structure-of-an-input) and have working examples for all of the types, but the object seems to get lost.

**To Reproduce**

I created a code sandbox with an example:
https://codesandbox.io/s/vue-formulate-nested-groups-2-forked-vzfsw

**Expected behavior**
I would expect that the object would be passed through as a prop.

**Comment by justin-schroeder** [comment]
Ah, so "options" is a reserved word since it's [already a prop](https://vueformulate.com/guide/inputs/#props). I switched your example to use `obj` instead and all is right as rain again:

https://codesandbox.io/s/object-options-passing-forked-slodd?file=/src/SearchInput.vue

If you really want to use the word "options" that's fine, but it will come through in the `context` object `context.options` and it will also be formatted to the [`optionList` syntax](https://github.com/wearebraid/vue-formulate/blob/master/src/libs/context.js#L393-L399). If that suits your use case you're golden, otherwise you'll need to use a different prop name. Best of luck 👍

**Comment by abrin** [comment]
Hmm... well that really bad luck. Thanks.  Would it make sense to add a warning or note in the documentation about prop collision?

**Comment by justin-schroeder** [comment]
Yep that's a great idea for the `slotProps` section of the docs 👍 Feel free to submit a PR to the docs for that otherwise we'll try to add it on the next round of updates
