### ISSUE TITLE
Input type number accept 'e' character

### ISSUE THREAD

**Issue by radeanu** [wearebraid/vue-formulate#414]
**Describe the bug**
Input type number accept 'e' character

**To Reproduce**
1. Create an input with type and validation = number
2. Type e character
4. See what input is valid

**Reproduction**
Check CodeSandbox example
### CodeSandbox
Example: https://codesandbox.io/s/peaceful-euclid-6misr?file=/src/App.vue

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48490432/113291640-faf8fb80-92fb-11eb-9381-7ed87c047541.PNG)

**Device information:**
 - Browser [Chrome - Version 89.0.4389.114]

**Comment by justin-schroeder** [comment]
Yeah, this is odd behavior, and it's browser dependent. The `number` input is just an HTML `<input type="number">` which behaves quite differently depending on the browser. On mobile safari for example, it doesn't even restrict the characters used by default.

In your example — specifically in chome — the character "e" is an incomplete numeric expression entry, so chome hasn't even reported that any value is input — that's why you get the "is required" error message — technically nothing has been entered even though there's an e. The reason the specific letter `e` is allowed in chrome is because chrome allows exponent numbers like `2.4e5`. But that's a browser implementation detail.

The inconsistency with numeric inputs is why a lot of UX people choose to use text inputs and just have the appropriate validation rules to guide the end user. Admittedly it's not ideal, but it's the web we live in at the moment. Hope this explanation helps — Good luck 👍
