### ISSUE TITLE
contextObserver do not call observers when the context changes

### ISSUE THREAD

**Issue by asattelmaier** [wearebraid/vue-formulate#421]
**Describe the bug**
If you register an Observer with addContextObserver Method from FormulateForm.vue, it will actually not Observe the Context, it will only call the provided callback once.

**To Reproduce**
1. Use the Vue Formulates Schema Feature.
2. Register a Component
3. Inject in the Component "observeContext"
4. Register a Observer by providing a Callback to "observeContext"

**Expected behavior**
The Observer should be notified if the Context changes. Technical speaking, the callback of each "contextObservers" list element should be called as soon as a FormContext value changed.

**Comment by justin-schroeder** [comment]
Hmm, the context observer system is not a published/public API, can you give a reproduction (codepen or codesandbox) of how you're trying to use it and in which way it's failing? Thanks

**Comment by asattelmaier** [comment]
observeContext will be provided by FormulateForm.vue
https://github.com/wearebraid/vue-formulate/blob/10ab31b4939323ed9d61cf810eddc676c4242bd1/src/FormulateForm.vue#L32

And as you can see in the Implementation, it will actually just call the callback function.
https://github.com/wearebraid/vue-formulate/blob/10ab31b4939323ed9d61cf810eddc676c4242bd1/src/FormulateForm.vue#L217

I will create later an example implementation.

**Comment by asattelmaier** [comment]
This is a sample implementation:
https://codesandbox.io/s/admiring-ritchie-ru2w5?file=/src/main.js

As a user of the Method, I would expect, that the provided callback will be called as soon as the form context changed. But if you invalidate the email input, the form context will change but the callback will not be called.

**Comment by asattelmaier** [comment]
I have created a sample implementation for a fix, I can create a pull request if this is the expected behaviour.

**Comment by justin-schroeder** [comment]
The contextObserver is not a published API, so unfortunately it really isnt intended to be used the way you're using it. the validity of a an entire form is supposed to be monitored using the default slot context object — which I understand isn't available when using schemas. However, I don't think we want to repurpose the existing injection for the schema purpose you're describing since its current use case is already fully implemented.

What I do think is meaningful in your issue is the fact that currently there is no way, when using a schema, to extract data normally available to scoped slots in template land. We'll need to work on this for V3
