### ISSUE TITLE
Emit events when validation occurs

### ISSUE THREAD

**Issue by Christoph-Wagner** [wearebraid/vue-formulate#43]
Whenever validation occurs, it would be nice to emit `validation` with the validationErrors array in the case of inputs or `{inputName: []}` for Forms. This would allow easily implementing your own handling of errors.

If that sounds good I could start on it, my current idea would be to do it in `.then(errorMessages => { this.validationErrors = errorMessages })` of `FormulateInput.performValidation`

**Comment by justin-schroeder** [comment]
@Christoph-Wagner makes sense to me, good feature addition. If you submit a PR target the `release/2.2.x` branch. One thing to note is you’ll receive a lot of events since the rules are evaluated on each input event. A few tests would be really helpful too.

Out of curiosity, what kind of external error handling are you looking to implement?

**Comment by Christoph-Wagner** [comment]
> Out of curiosity, what kind of external error handling are you looking to implement?

That was more my reasoning for others (seen it in a lot of similar libraries)

The reason I thought of it, is that I need to resize an iframe the Vue form is loaded in whenever anything size wise changes. The joys of working with Vue in a legacy ASP.NET webforms application that has everything inside a `<form>` and throws up when you nest a form inside it :D

**Comment by justin-schroeder** [comment]
Ah...yeah. Makes sense. Seems like it would be worth placing this event on `FormulateForm` too so you can detect any form errors in one pass.

**Comment by Christoph-Wagner** [comment]
I was looking into this and it seems all the error properties on the form are always empty, same for the ErrorObserver. Am I missing something or is that behavior that is not yet done?

**Comment by justin-schroeder** [comment]
The error properties and error observers on the form are for passing [form and field level errors](https://vueformulate.com/guide/forms/error-handling/#manual-error-handling) (new feature `2.2.0` like for backend error handling) down to individual fields or at the form level — pretty cool feature I think, but I'm biased.

For your purposes of determining if an entire form should resize we would need a way of exposing the field validation errors to the form. Currently the form can _know_ if there are field validation errors (`hasValidationErrors()`) on its child fields, but currently it doesn't know what they are or if/when they change. So that piece of it would probably require a bit of additional plumbing.

**Comment by Christoph-Wagner** [comment]
Thanks, misunderstood what they do. I’ll see about building the parts to let the form emit a nice event over the weekend. For my purpose it would be easy enough to just use the event on the input elements, but might as well do it right ;)

**Comment by justin-schroeder** [comment]
This is in the `release/2.3.0` branch and will ship with `v2.3.0`. Thanks to @Christoph-Wagner.
