### ISSUE TITLE
Calling function in Input Button not working

### ISSUE THREAD

**Issue by M457ERCH1EF** [wearebraid/vue-formulate#48]
**Describe the bug**
Calling function in Input Button not working.

**To Reproduce**
`<FormulateInput
                        type="button"
                        label="Show Dialog"
                        v-on:click="showdialog()"
                      />`

**My Function**
`showdialog () {
        this.showformDialog = true
}`

**Comment by justin-schroeder** [comment]
@M457ERCH1EF since the `FormulateInput` is not a "native" element, you’ll [need to use the native modifier](https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed):

```vue
<FormulateInput type="button" label="Show Dialog" v-on:click.native="showdialog()" />
```

We might consider having the button emit a click event in the future, but this is a normal behavior.

If you have further issues, feel free to ask.

**Comment by M457ERCH1EF** [comment]
Highly appreciate it. It works now tq.
