### ISSUE TITLE
Make scss variables of themes customizable

### ISSUE THREAD

**Issue by mooori** [wearebraid/vue-formulate#481]
I would like to use the snow theme, but with my site's font instead of the given value of `$formulate-font-stack`.

In `Dart Sass` there is an [API for configuring modules](https://sass-lang.com/documentation/variables#configuring-modules). This would make the following possible:

```scss
@use '~@braid/vue-formulate/themes/snow/snow' with (
  $formulate-font-stack: "My Font"
);
```

This requires the variables to be at the theme's top level stylesheet with `!default` flag.

Would it be possible to move the variables accordingly? Respectively, does it make sense in terms of costs vs benefits?

AFAIK there's currently no way for users to customize variables like `$formulate-font-stack` directly.

**Comment by andrew-boyd** [comment]
@mooori - Happy to do this. I'll make the changes and get a PR in the works for publishing. In the mean time, you can feel free to copy the base snow theme into your own project and add the `!default` flags yourself since I cannot think of a reason that the stylesheet will change in the near future before `!default` is included in the package itself.

**Comment by mooori** [comment]
Great, thanks for adding this right away @andrew-boyd.

Apparently it's not necessary to move the variables to the top level stylesheet `snow.scss`. Just tested it and adding `!default` as in #482 suffices to make `@use ... with ...` work.

I guess this might be useful for others as well. Currently it requires some digging into `snow` and knowing of the `@use ... with ...` sass feature. So I'm preparing a pull request to mention this in the guide.
