### ISSUE TITLE
Select all feature for checkbox with options.

### ISSUE THREAD

**Issue by carrera** [wearebraid/vue-formulate#49]
**Describe the new feature you'd like**
A select all toggle for checkboxes with options.

**What percentage of vue-formulate users would benefit?**
80%

**Comment by justin-schroeder** [comment]
Not a bad idea, in the meantime, you can do it this way:

```vue
<template>
  <div class="">
    <FormulateInput
      v-model="selection"
      type="checkbox"
      options="colors"
    />
   <span
      @click="selection = Object.keys(colors)"
      v-text="Select all"
   />
  </div>
</template>

<script>
export default {
  data () {
     return {
       colors: { red: 'Red', green: 'Green', blue: 'Blue' },
       selection: []
     }
  },
}
</script>
```

And obviously set `selection` to [] to unselect all.

**Comment by carrera** [comment]
Thanks, i already had something for it but would be a cool builtin feature

**Comment by justin-schroeder** [comment]
I think I'm landing on not including this as a feature for now. We need to be careful about the total-size of the package, and since it's already supported (as in it's possible) I'm going to remove this from the roadmap.

That said — i'll leave comments open and if it resurfaces by popular demand we'll look into it again.
