### ISSUE TITLE
Add Number Keypad for Mobile Number / Postal Code Input

### ISSUE THREAD

**Issue by joeelia** [wearebraid/vue-formulate#5]
Add something like this for number inputs:

`<input type=”text” inputmode=”numeric” pattern="[0-9]*">`

It would help with accessibility, for since the buttons on mobile will be bigger and this pattern is being recognized by (https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)

**Comment by justin-schroeder** [comment]
Interesting, thanks for bringing this to my attention. Im hesitant to make this the default/only behavior since that would be a breaking change. But perhaps the addition of a new “numeric” I put type could be useful for these use cases. Although several countries use letters in postal codes too.

Either way, Vue Formulate automatically passes any attributes down to the root input element, so you can create this behavior today. 👍

https://codepen.io/justin-schroeder/pen/Poqmyba

*(The lowercase/hyphen syntax is necessary when using vue-formulate via CDN)*

**Comment by justin-schroeder** [comment]
@joeelia thanks again for this suggestion. I've added this as a suggestion to the `number` input in the documentation. https://vueformulate.com/guide/inputs/text/#number
