### ISSUE TITLE
Can't seem to extract the url from Vue Formulate File Input

### ISSUE THREAD

**Issue by BenjaminAlamu** [wearebraid/vue-formulate#505]
I am having issues with extracting the url from thr file input

  ```  <FormulateInput
      v-if="field.type === 'file'"
      id="file"
      type="file"
      name="file"
      v-model="image"
      label="Upload your profile picture here"
      help=""
      validation="mime:image/jpeg,image/jpg,image/png"
    />```
    
    ```  watch: {
    image(newVal, oldVal) {
      console.log({ newVal: newVal.files[0].path });
    }
  },```
  
  The console.log always returns false instead of an object with the url and the path

**Comment by justin-schroeder** [comment]
Hey @BenjaminAlamu. The docs don't specify anything like files[0].path so certainly that wouldn't work. There's pretty extensive documentation on how to use file inputs here:

https://vueformulate.com/guide/inputs/types/file/#upload-results-with-v-model-on-formulateinput

If you think you've identified a bug, it would be super helpful to create a codepen or a codesandbox.

Good luck! 👍

**Comment by BenjaminAlamu** [comment]
Hi @justin-schroeder 

I haven't been able to get the result of the upload to be saved in the v-model of the file input
I have added value but that still doesn't work

**Comment by justin-schroeder** [comment]
If you post a codepen or codesandbox im happy to take a look!

**Comment by BenjaminAlamu** [comment]
Hi @justin-schroeder 

Here's a codepen link
https://codepen.io/BenjaminAlamu/pen/zYdNXeo

**Comment by justin-schroeder** [comment]
Here's a fork of your code with a working extraction. The `upload()` function is idempotent so its ok to call it again to retrieve the url/path data. Also I removed the `:value` in favor of a `v-model` because in Vue Formulate `:value` is only used to set initial values, it does not perform model binding (vue doesnt support that except for v-model)

Have a great week @BenjaminAlamu!

https://codepen.io/justin-schroeder/pen/JjyWRGY
