### ISSUE TITLE
Troubleshooting repeatable form groups

### ISSUE THREAD

**Issue by henryaj** [wearebraid/vue-formulate#522]
**Describe the bug**
Strange behaviour with radio buttons in repeating form groups. In the second element and onwards, radio buttons are briefly shown with the correct state, and then revert to being cleared. The bound form values are correct, however.

Here's a video showing the behaviour in question:

https://user-images.githubusercontent.com/1193856/150828780-22bc7b29-2d58-4123-b912-31f998e24dda.mov

Notice how, on page refresh, the radio button is filled in - and then after a moment it becomes empty again. But the adjacent field, which uses a `v-if` directive to hide/show depending on what this input contains, still works as expected.

I managed to get around the problem in an odd way - I made a copy of FormulateInputBox.vue which replaces the original one from the library. The only difference is in the computed `attributes` value, in which the library version does this:

```js
attributes () {
  return this.context.attributes || {}
},
```

and my version instead does this:

```js
attributes () {
  let attr = this.context.attributes || {}
  delete attr.name
  return attr
},
```

which for some reason resolves the issue without apparently breaking any other behaviour (validation, hydrating the form and saving the form all work as intended).

**Comment by justin-schroeder** [comment]
Thanks for the quality report. Unfortunately this is a known issue that doesn't have a great solution in Vue Formulate — in fact its one of the reasons for the FormKit re-write (new architecture gives us much better control) The crux of the issue is that in HTML radios with the same `name` are "bound" together — thats how HTML knows which radios should work together.

Since the repeater is just repeating the slot provided the name of the radios is the same, and you end up with this really bizzare behavior. A solution tot his is to add the `context.index` to the name of the radio. The downside is our form data with include this in the name. Your solution to delete the name is interesting too, although im not sure that will have reliable results for the group of inputs.
