### ISSUE TITLE
Toggle Password Visibility

### ISSUE THREAD

**Issue by dextersiah** [wearebraid/vue-formulate#528]
It would be nice to have an option for password type inputs to have the eye toggle for toggling the visibility of the password. 

Fairly certain that having the eye toggle is very common on password fields and it would be great to have that built in without having to create a custom input component for it.

**Comment by justin-schroeder** [comment]
This is a pretty common use case! I'd recommend dynamically changing the `type` of input from a password to a text and use the suffix slot to add the eye ball. Unfortunately this isn't something we'll be implementing in Vue Formulate since it draws a pretty strict line around the bounds of "native" inputs (its not trying to be a a component framwork)

That said, [FormKit](https://www.formkit.com) Vue Formulate’s successor would be much more likely to implement a feature like this 👍
