### ISSUE TITLE
Add ability to append files to "multiple" upload

### ISSUE THREAD

**Issue by kgierke** [wearebraid/vue-formulate#54]
**Describe the new feature you'd like**
Add the ability to add more files or images to a file input, after files have already been selected. Currently the only option is to remove all files before adding new ones. The best option would probably be to add a prop to allow for adding files/images.

This feature would eliminate the need to re-select all files/images if you missed some on the first time, reduce the amount of uploads (`upload-behaviour="live"`) and gives to opportunity to add files on fields with pre-filled files/images.

This option should only be available to inputs with the `multiple` prop.

**What percentage of vue-formulate users would benefit?**
80%

**Comment by justin-schroeder** [comment]
Good idea! I don't think it's going to be a cake walk to implement but I definitely understand the value. 

If you're interested in submitting a PR, you'll want to take a look at the [FileUpload](https://github.com/wearebraid/vue-formulate/blob/master/src/FileUpload.js) class. Because [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) is basically immutable it can be challenging to work with, but a starting point is understanding how the it works when "removing" files (we create a new file list using the [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer) API normally used for Drag/Drop)

**Comment by thunderwin** [comment]
Oh we need this function like now.. what can we do here..

**Comment by justin-schroeder** [comment]
Ah, sorry but this definitely isn’t ready yet 😕.

A sub-optimal “today”option would be to use a repeatable `group` input with a `file` in it that is not “multiple”. Then you could add/remove multiple files at will, but the UI wouldn’t be ideal.

Also open to anyone submitting a pull request, it’s a self contained enough problem it’s not a bad option for someone in the community to tackle!

**Comment by thunderwin** [comment]
use group sounds like a good idea.  I will try

I would like to submit some pull requests. but I m not a pro ..so.  I will do some translation work later..  like Chinese..

**Comment by justin-schroeder** [comment]
@thunderwin I've been itching to see a Chinese translation. In fact China is the #3 most frequent country to visit the documentation, but we [vue-formulate-i18n](https://github.com/wearebraid/vue-formulate-i18n) doesn't have a Chinese translation yet :(

**Comment by Yiddishe-Kop** [comment]
bump 👀

**Comment by justin-schroeder** [comment]
Put it on the roadmap for 2.5 😉

**Comment by justin-schroeder** [comment]
Ok, this feature is now added and part of the `release/2.5.0` branch — including backing cypress tests (finally). Early docs for 2.5 are here:

https://vueformulatecom-git-release-250.braid.vercel.app/guide/inputs/types/file/#file-2
