### ISSUE TITLE
Tab Order

### ISSUE THREAD

**Issue by karahan** [wearebraid/vue-formulate#63]
Yooo, i got a new one :P

**Describe the new feature you'd like**
Passing tab order as a prop

**What percentage of vue-formulate users would benefit?**
40%

**Comment by justin-schroeder** [comment]
@karahan This should work as you want today actually. Just add a `tabindex` attribute:

```vue
<FormulateInput
  type="text"
  name="username"
  tabindex="0"
/>
```

These are not technically "props", they are just attributes. VueFormulate passes down all attributes (except `class`) to the root input element, which is why each of these is not documented (would have to re-document all HTML attributes 😳)

I'll re-open this if this was not what you were looking for. Good luck! 👍
