### ISSUE TITLE
Input File/Image uploader prop

### ISSUE THREAD

**Issue by gelzavier** [wearebraid/vue-formulate#82]
When using a FormulateForm with FormulateInput type image, I wish to keep the uploader prop, so I can use it for Parse server File Upload.

Example:
```
<template>
    <div>
            <FormulateForm
                    class="login-form"
                    @submit="setImage"
            >
                <FormulateInput
                        type="text"
                        name="name"
                        label="Image Name"
                        placeholder="image name..."
                        validation="required"
                />

                <FormulateInput
                        type="image"
                        name="image"
                        label="Select an image to upload"
                        help="Select a png, jpg or gif to upload."
                        validation="mime:image/jpeg,image/png,image/gif"
                        upload-behavior="delayed"
                        :uploader="uploadImage"
                />

                <FormulateInput
                        type="submit"
                        label="Add an Image"
                />

            </FormulateForm>
    </div>
</template>
<script>
export default {
        data() {
            return {
                upImgProps: {}
            }
        },
        methods: {
            setImage(data) {
                this.$store.dispatch('a_uploadImage', {data, ...this.upImgProps});
            },
            uploadImage(file, progress, error, option) {
                this.upImgProps = {file, progress, error, option};
            }
        }
    }
</script>
```
As shown in code above, I can accomplish this by attaching 2 methods. The question is, is there a simpler way that i use the submit event, at time same time access the image' uploader props (file, progress ... etc)?

**Comment by justin-schroeder** [comment]
@gelzavier you cannot access the uploader props in the submit handler itself, but the uploader is called automatically when the submit event is called. 

If it was my code, I would make your `uploadImage` to dispatch the image upload and await for the requested data (`[{url}]`). Then when your submit handler is called it will already have the uploaded data in the data prop.

Since you're using a vuex action you really shouldn't return your value so you would need to get the return out of the store which is one more step but pretty doable. You're also able to use any of the form values (like the image name) by adding a `v-model` on the field or form.
