### ISSUE TITLE
Update the guide "Generate forms" with error handling

### ISSUE THREAD

**Issue by Rednas83** [wearebraid/vue-formulate#92]
I am trying to raise an error as soon as the input value is different then "Rednas" 
![image](https://user-images.githubusercontent.com/25219229/82831745-8d996480-9eb9-11ea-8976-caffaa8edb4f.png)
![image](https://user-images.githubusercontent.com/25219229/82832431-54fa8a80-9ebb-11ea-92ef-309f53f8dce9.png)
**Tried:**
data.name => works but of course if the name is set to name and only when in async because otherwise data is not initialized yet
@input="emit = $emit" => returns a function?

**Comment by justin-schroeder** [comment]
Hey Rednas83.

I'm not entirely sure what’s youre trying to achieve, but you should not be writing your own mechanism for validation, and there is no need to tap into the input event. Your example would be easily solved using vue formulate's validation rules.

```vue
<FormulateInput
  v-for=-"item in items"
  :key="item.name"
  v-bind="item"
  validation="in:Rednas"
  :validation-messages="{
    in: 'That username is already taken'
  }"
/>
```

If you actually want to check the status of validation from the backend, you would write a custom validation rule.

The `error` prop is only when you want to explicitly pass in an error value, usually from the backend on submission. It's rare that you would need it. 

@andrew-boyd wrote a nice article that uses some custom validators if you need an example: https://blog.logrocket.com/easier-more-robust-vue-forms-with-vue-formulate/

Docs on this: https://vueformulate.com/guide/validation/#custom-validation-rules

I'm going to close this for now since there's no bug or feature request here, but happy to carry on the conversation.

**Comment by Rednas83** [comment]
Thanks  for the example. That will work for me. 

I only moved validation and validation-messages to items as well.

Also I figured out that I had to use $event instead of $emit to get the emitted value
![image](https://user-images.githubusercontent.com/25219229/82843770-83d62800-9ede-11ea-9d2d-4b6098aa71f7.png)
